// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqm1t2a5x6yb6K1jrDuEiEO4sfffSke4Q',
    appId: '1:215591499374:web:4a1f8fb2242528428dd87f',
    messagingSenderId: '215591499374',
    projectId: 'collabws-3ae84',
    authDomain: 'collabws-3ae84.firebaseapp.com',
    databaseURL: 'https://collabws-3ae84-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'collabws-3ae84.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxT-LYIWFTPLEqpJj6QVfJJyt1ko2svdg',
    appId: '1:215591499374:android:18a1dbb3b4633d508dd87f',
    messagingSenderId: '215591499374',
    projectId: 'collabws-3ae84',
    databaseURL: 'https://collabws-3ae84-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'collabws-3ae84.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbiyVzFPibs0Cxlm2h9T_ZlovnECBHzP4',
    appId: '1:215591499374:ios:09e5cef6a354cf398dd87f',
    messagingSenderId: '215591499374',
    projectId: 'collabws-3ae84',
    databaseURL: 'https://collabws-3ae84-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'collabws-3ae84.appspot.com',
    iosClientId: '215591499374-r19e34ihvf4pkjiu6b9e0g1voh2ijsj2.apps.googleusercontent.com',
    iosBundleId: 'com.example.collabWs',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbiyVzFPibs0Cxlm2h9T_ZlovnECBHzP4',
    appId: '1:215591499374:ios:09e5cef6a354cf398dd87f',
    messagingSenderId: '215591499374',
    projectId: 'collabws-3ae84',
    databaseURL: 'https://collabws-3ae84-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'collabws-3ae84.appspot.com',
    iosClientId: '215591499374-r19e34ihvf4pkjiu6b9e0g1voh2ijsj2.apps.googleusercontent.com',
    iosBundleId: 'com.example.collabWs',
  );
}
